---------------------------------------------------------
--  DDL para almacenar visitas  por día
---------------------------------------------------------
DROP TABLE INDICATORS_AVAILABILITY;

CREATE TABLE INDICATORS_AVAILABILITY(
  INDICATOR_ID NUMBER(10,0) NOT NULL,
  HOTEL VARCHAR2(20) NOT NULL,
  LOCATION1 VARCHAR2(50) NOT NULL,
  ORIGIN VARCHAR2(20) NOT NULL,
  DESTINATION VARCHAR2(20) NOT NULL,
  SCORE FLOAT(10),
  AVAILABILITY_SEARCH_TIMES NUMBER(9,0) DEFAULT 0 NOT NULL,
  INDICATOR_DATE TIMESTAMP (6) DEFAULT SYSDATE,
  CREATED_DATE TIMESTAMP (6) DEFAULT SYSDATE,
  UPDATED_DATE TIMESTAMP (6) DEFAULT SYSDATE,
  CONSTRAINT INDICATOR_KEY PRIMARY KEY (INDICATOR_ID)
)

select * from INDICATORS_AVAILABILITY;

--key que utiliza HotelsCombined
insert into INDICATORS_AVAILABILITY(INDICATOR_ID,HOTEL, LOCATION1, ORIGIN, DESTINATION, SCORE, AVAILABILITY_SEARCH_TIMES, INDICATOR_DATE) values (3, 'HOTEL1234', 'hotel:LH_Plaza_Santa_Ana', 'Barcelona', 'Madrid', 4, 5, TO_DATE('2017/12/11 13:30:25', 'YYYY/MM/DD HH24:MI:SS'));
insert into INDICATORS_AVAILABILITY(INDICATOR_ID,HOTEL, LOCATION1, ORIGIN, DESTINATION, SCORE, AVAILABILITY_SEARCH_TIMES, INDICATOR_DATE) values (4, 'HOTEL6788', 'hotel:Eric_Vokel_Boutique_Apartments_Atocha_Suites', 'Barcelona', 'Madrid', 4, 5, TO_DATE('2017/12/11 13:30:25', 'YYYY/MM/DD HH24:MI:SS'));